# AI-Based Recruitment Screening Lab

## Lab Objective
The objective of this lab is to help learners understand how an AI-assisted recruitment system works at a basic level by:

1. Creating a small synthetic candidate dataset with 20 rows.
2. Understanding candidate attributes such as skills, experience, education, and certifications.
3. Comparing candidate resumes with a job description.
4. Using TF-IDF and cosine similarity to measure resume-job matching.
5. Creating a simple weighted scoring model for ranking candidates.
6. Generating a shortlist of top candidates.
7. Interpreting the result from an HR decision-making perspective.

## Learning Outcome
By the end of this lab, students will be able to:
- Explain how recruitment data can be structured for analysis.
- Apply basic text-based AI matching in hiring.
- Build a simple rule-based + AI-assisted candidate ranking workflow.
- Understand that AI supports HR decisions, but does not replace human judgment.

## Step 1: Import Required Libraries

In [1]:
# This cell imports all the libraries required in the lab.
# pandas is used for working with tabular data.
# numpy is used for numerical operations.
# sklearn is used for text vectorization and similarity calculation.

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# This line improves the display of tables in notebooks.
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

## Step 2: Create a Synthetic Recruitment Dataset (20 Rows)

In [2]:
# This cell creates a synthetic dataset of 20 candidates.
# Each row represents one candidate.
# The fields are designed to simulate basic recruitment information.

data = [
    {"candidate_id": 1, "name": "Aarav", "skills": "python sql machine learning excel", "experience_years": 3, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 2, "name": "Diya", "skills": "excel communication recruitment onboarding", "experience_years": 4, "education": "MBA HR", "certifications": 1},
    {"candidate_id": 3, "name": "Kabir", "skills": "python pandas data analysis sql tableau", "experience_years": 2, "education": "B.Sc", "certifications": 3},
    {"candidate_id": 4, "name": "Ishita", "skills": "java sql spring communication teamwork", "experience_years": 5, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 5, "name": "Vivaan", "skills": "python sql deep learning nlp bert", "experience_years": 6, "education": "M.Tech", "certifications": 4},
    {"candidate_id": 6, "name": "Anaya", "skills": "recruitment sourcing interview screening communication", "experience_years": 3, "education": "MBA HR", "certifications": 2},
    {"candidate_id": 7, "name": "Reyansh", "skills": "python sql power bi excel statistics", "experience_years": 4, "education": "B.Tech", "certifications": 2},
    {"candidate_id": 8, "name": "Myra", "skills": "machine learning python data visualization tableau", "experience_years": 2, "education": "M.Sc", "certifications": 3},
    {"candidate_id": 9, "name": "Arjun", "skills": "manual testing selenium jira communication", "experience_years": 5, "education": "BCA", "certifications": 1},
    {"candidate_id": 10, "name": "Siya", "skills": "python sql ml nlp communication teamwork", "experience_years": 3, "education": "MCA", "certifications": 3},
    {"candidate_id": 11, "name": "Krish", "skills": "excel sql reporting dashboard power bi", "experience_years": 2, "education": "B.Com", "certifications": 2},
    {"candidate_id": 12, "name": "Aadhya", "skills": "python r statistics machine learning", "experience_years": 4, "education": "M.Stat", "certifications": 3},
    {"candidate_id": 13, "name": "Advik", "skills": "project management agile scrum communication", "experience_years": 6, "education": "MBA", "certifications": 2},
    {"candidate_id": 14, "name": "Kiara", "skills": "python sql data analysis recruitment hr analytics", "experience_years": 5, "education": "MBA HR", "certifications": 4},
    {"candidate_id": 15, "name": "Atharv", "skills": "c++ algorithms data structures problem solving", "experience_years": 1, "education": "B.Tech", "certifications": 1},
    {"candidate_id": 16, "name": "Navya", "skills": "python sql tableau power bi communication", "experience_years": 3, "education": "BBA", "certifications": 2},
    {"candidate_id": 17, "name": "Rudra", "skills": "nlp bert transformers python machine learning", "experience_years": 5, "education": "M.Tech", "certifications": 4},
    {"candidate_id": 18, "name": "Sara", "skills": "recruitment analytics excel communication hr operations", "experience_years": 4, "education": "MBA HR", "certifications": 2},
    {"candidate_id": 19, "name": "Vihaan", "skills": "python sql statistics data cleaning pandas", "experience_years": 2, "education": "B.Sc", "certifications": 2},
    {"candidate_id": 20, "name": "Meera", "skills": "python machine learning sql communication dashboards", "experience_years": 4, "education": "MCA", "certifications": 3}
]

df = pd.DataFrame(data)

print("Synthetic dataset created successfully.")
df

Synthetic dataset created successfully.

    candidate_id     name                                             skills  experience_years education  certifications
0              1    Aarav                  python sql machine learning excel                 3    B.Tech               2
1              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1
2              3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3
3              4   Ishita             java sql spring communication teamwork                 5    B.Tech               2
4              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4
5              6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2
6              7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2
7              8     Myra  machine learning python data visualization tab...                 2      M.Sc               3
8              9    Arjun         manual testing selenium jira communication                 5       BCA               1
9             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3
10            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2
11            12   Aadhya               python r statistics machine learning                 4    M.Stat               3
12            13    Advik       project management agile scrum communication                 6       MBA               2
13            14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4
14            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1
15            16    Navya          python sql tableau power bi communication                 3       BBA               2
16            17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4
17            18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2
18            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2
19            20    Meera  python machine learning sql communication dash...                 4       MCA               3

## Step 3: Understand the Dataset Shape and Columns

In [3]:
# This cell checks the size of the dataset and the column names.
# shape tells us how many rows and columns are present.
# columns tells us the names of all variables in the dataset.

print("Dataset shape:", df.shape)
print("Column names:", list(df.columns))

Dataset shape: (20, 6)
Column names: ['candidate_id', 'name', 'skills', 'experience_years', 'education', 'certifications']

## Step 4: Basic Data Inspection

In [4]:
# This cell displays the first few rows of the dataset.
# head() is useful for quickly checking whether the data looks correct.

df.head()

   candidate_id    name                                      skills  experience_years education  certifications
0             1   Aarav           python sql machine learning excel                 3    B.Tech               2
1             2    Diya  excel communication recruitment onboarding                 4    MBA HR               1
2             3   Kabir     python pandas data analysis sql tableau                 2      B.Sc               3
3             4  Ishita      java sql spring communication teamwork                 5    B.Tech               2
4             5  Vivaan           python sql deep learning nlp bert                 6    M.Tech               4

## Step 5: Define a Job Description

In [5]:
# This cell defines the target job description.
# In a real recruitment system, this text would come from an actual job posting.
# We keep it short and relevant for learning purposes.

job_description = "python sql machine learning nlp communication dashboards recruitment analytics"

print("Job Description:")
print(job_description)

Job Description:
python sql machine learning nlp communication dashboards recruitment analytics

## Step 6: Convert Resume Skills and Job Description into Numerical Form Using TF-IDF

In [6]:
# This cell uses TF-IDF Vectorizer.
# TF-IDF stands for Term Frequency - Inverse Document Frequency.
# It converts text into numbers based on the importance of words.
# We combine the job description and candidate skills in one list
# so that both can be represented in the same vector space.

documents = [job_description] + df["skills"].tolist()

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (21, 46)

## Step 7: Calculate Cosine Similarity Between Job Description and Candidate Skills

In [7]:
# This cell calculates cosine similarity.
# Cosine similarity measures how similar two text vectors are.
# A value closer to 1 means higher similarity.
# A value closer to 0 means lower similarity.

job_vector = tfidf_matrix[0:1]
candidate_vectors = tfidf_matrix[1:]

similarity_scores = cosine_similarity(job_vector, candidate_vectors).flatten()

df["similarity_score"] = similarity_scores

print("Cosine similarity scores calculated successfully.")
df[["candidate_id", "name", "skills", "similarity_score"]]

Cosine similarity scores calculated successfully.

    candidate_id     name                                             skills  similarity_score
0              1    Aarav                  python sql machine learning excel          0.461985
1              2     Diya         excel communication recruitment onboarding          0.246840
2              3    Kabir            python pandas data analysis sql tableau          0.113584
3              4   Ishita             java sql spring communication teamwork          0.128840
4              5   Vivaan                  python sql deep learning nlp bert          0.373774
5              6    Anaya  recruitment sourcing interview screening commu...          0.188620
6              7  Reyansh               python sql power bi excel statistics          0.119317
7              8     Myra  machine learning python data visualization tab...          0.275516
8              9    Arjun         manual testing selenium jira communication          0.061943
9             10     Siya           python sql ml nlp communication teamwork          0.349575
10            11    Krish             excel sql reporting dashboard power bi          0.052342
11            12   Aadhya               python r statistics machine learning          0.382899
12            13    Advik       project management agile scrum communication          0.061943
13            14    Kiara  python sql data analysis recruitment hr analytics          0.406514
14            15   Atharv     c++ algorithms data structures problem solving          0.000000
15            16    Navya          python sql tableau power bi communication          0.204367
16            17    Rudra      nlp bert transformers python machine learning          0.418469
17            18     Sara  recruitment analytics excel communication hr o...          0.364453
18            19   Vihaan         python sql statistics data cleaning pandas          0.109594
19            20    Meera  python machine learning sql communication dash...          0.755230

## Step 8: Normalize Experience and Certifications for Fair Scoring

In [8]:
# This cell scales experience and certifications to a 0 to 1 range.
# Normalization is important because experience and certifications
# are measured on different numeric scales.

df["experience_score"] = df["experience_years"] / df["experience_years"].max()
df["certification_score"] = df["certifications"] / df["certifications"].max()

df[["name", "experience_years", "experience_score", "certifications", "certification_score"]]

       name  experience_years  experience_score  certifications  certification_score
0     Aarav                 3          0.500000               2                 0.50
1      Diya                 4          0.666667               1                 0.25
2     Kabir                 2          0.333333               3                 0.75
3    Ishita                 5          0.833333               2                 0.50
4    Vivaan                 6          1.000000               4                 1.00
5     Anaya                 3          0.500000               2                 0.50
6   Reyansh                 4          0.666667               2                 0.50
7      Myra                 2          0.333333               3                 0.75
8     Arjun                 5          0.833333               1                 0.25
9      Siya                 3          0.500000               3                 0.75
10    Krish                 2          0.333333               2                 0.50
11   Aadhya                 4          0.666667               3                 0.75
12    Advik                 6          1.000000               2                 0.50
13    Kiara                 5          0.833333               4                 1.00
14   Atharv                 1          0.166667               1                 0.25
15    Navya                 3          0.500000               2                 0.50
16    Rudra                 5          0.833333               4                 1.00
17     Sara                 4          0.666667               2                 0.50
18   Vihaan                 2          0.333333               2                 0.50
19    Meera                 4          0.666667               3                 0.75

## Step 9: Convert Education into a Simple Numerical Score

In [9]:
# This cell maps education levels into a simple score.
# This is only for demonstration.
# In real hiring, education should be interpreted carefully and ethically.

education_map = {
    "B.Com": 0.50,
    "BBA": 0.55,
    "BCA": 0.55,
    "B.Sc": 0.60,
    "B.Tech": 0.70,
    "MBA": 0.75,
    "MBA HR": 0.80,
    "MCA": 0.80,
    "M.Sc": 0.80,
    "M.Tech": 0.90,
    "M.Stat": 0.90
}

df["education_score"] = df["education"].map(education_map)

df[["name", "education", "education_score"]]

       name education  education_score
0     Aarav    B.Tech             0.70
1      Diya    MBA HR             0.80
2     Kabir      B.Sc             0.60
3    Ishita    B.Tech             0.70
4    Vivaan    M.Tech             0.90
5     Anaya    MBA HR             0.80
6   Reyansh    B.Tech             0.70
7      Myra      M.Sc             0.80
8     Arjun       BCA             0.55
9      Siya       MCA             0.80
10    Krish     B.Com             0.50
11   Aadhya    M.Stat             0.90
12    Advik       MBA             0.75
13    Kiara    MBA HR             0.80
14   Atharv    B.Tech             0.70
15    Navya       BBA             0.55
16    Rudra    M.Tech             0.90
17     Sara    MBA HR             0.80
18   Vihaan      B.Sc             0.60
19    Meera       MCA             0.80

## Step 10: Build a Weighted Candidate Score

In [10]:
# This cell creates a final weighted score.
# We assign:
# 50% weight to similarity score
# 25% weight to experience score
# 15% weight to education score
# 10% weight to certification score
#
# These weights are only for teaching purposes.
# Organizations may define different weights based on role requirements.

df["final_score"] = (
    0.50 * df["similarity_score"] +
    0.25 * df["experience_score"] +
    0.15 * df["education_score"] +
    0.10 * df["certification_score"]
)

df[["name", "similarity_score", "experience_score", "education_score", "certification_score", "final_score"]]

       name  similarity_score  experience_score  education_score  certification_score  final_score
0     Aarav          0.461985          0.500000             0.70                 0.50     0.510992
1      Diya          0.246840          0.666667             0.80                 0.25     0.435087
2     Kabir          0.113584          0.333333             0.60                 0.75     0.305125
3    Ishita          0.128840          0.833333             0.70                 0.50     0.427753
4    Vivaan          0.373774          1.000000             0.90                 1.00     0.671887
5     Anaya          0.188620          0.500000             0.80                 0.50     0.389310
6   Reyansh          0.119317          0.666667             0.70                 0.50     0.381325
7      Myra          0.275516          0.333333             0.80                 0.75     0.416091
8     Arjun          0.061943          0.833333             0.55                 0.25     0.346805
9      Siya          0.349575          0.500000             0.80                 0.75     0.494788
10    Krish          0.052342          0.333333             0.50                 0.50     0.234504
11   Aadhya          0.382899          0.666667             0.90                 0.75     0.568116
12    Advik          0.061943          1.000000             0.75                 0.50     0.443472
13    Kiara          0.406514          0.833333             0.80                 1.00     0.631590
14   Atharv          0.000000          0.166667             0.70                 0.25     0.171667
15    Navya          0.204367          0.500000             0.55                 0.50     0.359683
16    Rudra          0.418469          0.833333             0.90                 1.00     0.652568
17     Sara          0.364453          0.666667             0.80                 0.50     0.518893
18   Vihaan          0.109594          0.333333             0.60                 0.50     0.278130
19    Meera          0.755230          0.666667             0.80                 0.75     0.739282

## Step 11: Rank Candidates from Highest to Lowest Score

In [11]:
# This cell sorts the candidates by final score in descending order.
# Highest score appears first, which means better fit according to the model.

ranked_df = df.sort_values(by="final_score", ascending=False).reset_index(drop=True)

ranked_df[["candidate_id", "name", "skills", "experience_years", "education", "certifications", "final_score"]]

    candidate_id     name                                             skills  experience_years education  certifications  final_score
0             20    Meera  python machine learning sql communication dash...                 4       MCA               3     0.739282
1              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4     0.671887
2             17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4     0.652568
3             14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4     0.631590
4             12   Aadhya               python r statistics machine learning                 4    M.Stat               3     0.568116
5             18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2     0.518893
6              1    Aarav                  python sql machine learning excel                 3    B.Tech               2     0.510992
7             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3     0.494788
8             13    Advik       project management agile scrum communication                 6       MBA               2     0.443472
9              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1     0.435087
10             4   Ishita             java sql spring communication teamwork                 5    B.Tech               2     0.427753
11             8     Myra  machine learning python data visualization tab...                 2      M.Sc               3     0.416091
12             6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2     0.389310
13             7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2     0.381325
14            16    Navya          python sql tableau power bi communication                 3       BBA               2     0.359683
15             9    Arjun         manual testing selenium jira communication                 5       BCA               1     0.346805
16             3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3     0.305125
17            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2     0.278130
18            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2     0.234504
19            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1     0.171667

## Step 12: Create a Shortlist of Top 5 Candidates

In [12]:
# This cell selects the top 5 candidates.
# These are the candidates most aligned with the job description
# according to the simple model created in this lab.

top_5 = ranked_df.head(5)

top_5[["candidate_id", "name", "skills", "experience_years", "education", "certifications", "final_score"]]

   candidate_id    name                                             skills  experience_years education  certifications  final_score
0            20   Meera  python machine learning sql communication dash...                 4       MCA               3     0.739282
1             5  Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4     0.671887
2            17   Rudra      nlp bert transformers python machine learning                 5    M.Tech               4     0.652568
3            14   Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4     0.631590
4            12  Aadhya               python r statistics machine learning                 4    M.Stat               3     0.568116

## Step 13: Add HR Interpretation

In [13]:
# This cell adds a recommendation label.
# It converts numeric scores into simple decision categories.

def label_candidate(score):
    if score >= 0.65:
        return "Strong Match"
    elif score >= 0.50:
        return "Moderate Match"
    else:
        return "Low Match"

ranked_df["recommendation"] = ranked_df["final_score"].apply(label_candidate)

ranked_df[["candidate_id", "name", "final_score", "recommendation"]]

    candidate_id     name  final_score  recommendation
0             20    Meera     0.739282    Strong Match
1              5   Vivaan     0.671887    Strong Match
2             17    Rudra     0.652568    Strong Match
3             14    Kiara     0.631590  Moderate Match
4             12   Aadhya     0.568116  Moderate Match
5             18     Sara     0.518893  Moderate Match
6              1    Aarav     0.510992  Moderate Match
7             10     Siya     0.494788       Low Match
8             13    Advik     0.443472       Low Match
9              2     Diya     0.435087       Low Match
10             4   Ishita     0.427753       Low Match
11             8     Myra     0.416091       Low Match
12             6    Anaya     0.389310       Low Match
13             7  Reyansh     0.381325       Low Match
14            16    Navya     0.359683       Low Match
15             9    Arjun     0.346805       Low Match
16             3    Kabir     0.305125       Low Match
17            19   Vihaan     0.278130       Low Match
18            11    Krish     0.234504       Low Match
19            15   Atharv     0.171667       Low Match

## Step 14: View Final Recruitment Output Table

In [14]:
# This cell shows the final output table.
# This output simulates the screening result that HR could review.

final_output = ranked_df[[
    "candidate_id",
    "name",
    "skills",
    "experience_years",
    "education",
    "certifications",
    "similarity_score",
    "experience_score",
    "education_score",
    "certification_score",
    "final_score",
    "recommendation"
]]

final_output

    candidate_id     name                                             skills  experience_years education  certifications  similarity_score  experience_score  education_score  certification_score  final_score  recommendation
0             20    Meera  python machine learning sql communication dash...                 4       MCA               3          0.755230          0.666667             0.80                 0.75     0.739282    Strong Match
1              5   Vivaan                  python sql deep learning nlp bert                 6    M.Tech               4          0.373774          1.000000             0.90                 1.00     0.671887    Strong Match
2             17    Rudra      nlp bert transformers python machine learning                 5    M.Tech               4          0.418469          0.833333             0.90                 1.00     0.652568    Strong Match
3             14    Kiara  python sql data analysis recruitment hr analytics                 5    MBA HR               4          0.406514          0.833333             0.80                 1.00     0.631590  Moderate Match
4             12   Aadhya               python r statistics machine learning                 4    M.Stat               3          0.382899          0.666667             0.90                 0.75     0.568116  Moderate Match
5             18     Sara  recruitment analytics excel communication hr o...                 4    MBA HR               2          0.364453          0.666667             0.80                 0.50     0.518893  Moderate Match
6              1    Aarav                  python sql machine learning excel                 3    B.Tech               2          0.461985          0.500000             0.70                 0.50     0.510992  Moderate Match
7             10     Siya           python sql ml nlp communication teamwork                 3       MCA               3          0.349575          0.500000             0.80                 0.75     0.494788       Low Match
8             13    Advik       project management agile scrum communication                 6       MBA               2          0.061943          1.000000             0.75                 0.50     0.443472       Low Match
9              2     Diya         excel communication recruitment onboarding                 4    MBA HR               1          0.246840          0.666667             0.80                 0.25     0.435087       Low Match
10             4   Ishita             java sql spring communication teamwork                 5    B.Tech               2          0.128840          0.833333             0.70                 0.50     0.427753       Low Match
11             8     Myra  machine learning python data visualization tab...                 2      M.Sc               3          0.275516          0.333333             0.80                 0.75     0.416091       Low Match
12             6    Anaya  recruitment sourcing interview screening commu...                 3    MBA HR               2          0.188620          0.500000             0.80                 0.50     0.389310       Low Match
13             7  Reyansh               python sql power bi excel statistics                 4    B.Tech               2          0.119317          0.666667             0.70                 0.50     0.381325       Low Match
14            16    Navya          python sql tableau power bi communication                 3       BBA               2          0.204367          0.500000             0.55                 0.50     0.359683       Low Match
15             9    Arjun         manual testing selenium jira communication                 5       BCA               1          0.061943          0.833333             0.55                 0.25     0.346805       Low Match
16             3    Kabir            python pandas data analysis sql tableau                 2      B.Sc               3          0.113584          0.333333             0.60                 0.75     0.305125       Low Match
17            19   Vihaan         python sql statistics data cleaning pandas                 2      B.Sc               2          0.109594          0.333333             0.60                 0.50     0.278130       Low Match
18            11    Krish             excel sql reporting dashboard power bi                 2     B.Com               2          0.052342          0.333333             0.50                 0.50     0.234504       Low Match
19            15   Atharv     c++ algorithms data structures problem solving                 1    B.Tech               1          0.000000          0.166667             0.70                 0.25     0.171667       Low Match

## Step 15: Save the Final Output as CSV

In [15]:
# This cell saves the final recruitment output into a CSV file.
# Students can download this file from Colab after running the cell.

final_output.to_csv("recruitment_screening_output.csv", index=False)

print("File saved successfully as recruitment_screening_output.csv")

File saved successfully as recruitment_screening_output.csv

## Step 16: Conclusion

This lab demonstrated a simple AI-assisted recruitment workflow:

- A synthetic dataset of 20 candidates was created.
- Candidate skill text was compared with a job description using TF-IDF and cosine similarity.
- Additional factors such as experience, education, and certifications were included in a weighted score.
- Candidates were ranked and shortlisted.
- The result showed how AI can support recruitment screening in a structured way.

## Important Note
This model is only for learning. In real recruitment:
- Data quality matters.
- Bias must be checked.
- Human judgment is essential.
- Final hiring decisions should never depend only on automated scores.

In [16]:
# ============================================================
# LAST CELL: SAVE FINAL OUTPUT AS CSV AND DOWNLOAD IT
# ============================================================

# Save DataFrame as CSV file
final_output.to_csv("resume_parsing_screening_output.csv", index=False)

print("CSV file created successfully.")

# Import Colab files module
from google.colab import files

# Automatically download file to your computer
files.download("resume_parsing_screening_output.csv")

CSV file created successfully.